const services = [
  {
    id: 'web-development',
    name: 'Web Development',
    description: 'Building responsive and dynamic websites tailored to client needs.',
    whyChooseUs: 'Our experienced team utilizes the latest technologies for quality delivery.',
    contactText: 'Tell us about your Web Development project.',
  },
  {
    id: 'mobile-development',
    name: 'Mobile App Development',
    description: 'Creating user-friendly mobile applications for iOS and Android platforms.',
    whyChooseUs: 'Our apps ensure an excellent user experience and high performance.',
    contactText: 'Tell us about your Mobile App Development project.',
  },
  {
    id: 'ecommerce-development',
    name: 'E-commerce Development',
    description: 'Developing robust online stores with secure payment gateways.',
    whyChooseUs: 'We build scalable e-commerce solutions that enhance customer engagement.',
    contactText: 'Discuss your E-commerce needs with us.',
  },
  {
    id: 'crm',
    name: 'CRM Development',
    description: 'Custom CRM solutions to streamline your business processes.',
    whyChooseUs: 'Our CRMs are designed to improve customer relationships and boost sales.',
    contactText: 'Let us know your CRM requirements.',
  },
  {
    id: 'ui-ux',
    name: 'UI/UX Design',
    description: 'Designing intuitive and attractive interfaces for better user engagement.',
    whyChooseUs: 'Our designs focus on user experience, ensuring ease of use and satisfaction.',
    contactText: 'Share your design ideas with us.',
  },
  {
    id: 'marketing',
    name: 'Digital Marketing',
    description: 'Implementing strategies to enhance your online presence and reach.',
    whyChooseUs: 'We use data-driven strategies to maximize your marketing ROI.',
    contactText: 'Let’s discuss your digital marketing strategy.',
  },
  {
    id: 'website-development',
    name: 'Website Development',
    description: 'End-to-end solutions for developing websites that drive engagement.',
    whyChooseUs: 'We ensure your website is optimized for both speed and performance.',
    contactText: 'Contact us for website development services.',
  },
  {
    id: 'web-app-development',
    name: 'Web App Development',
    description: 'Building scalable web applications to meet diverse business needs.',
    whyChooseUs: 'Our web apps are built with scalability and performance in mind.',
    contactText: 'Tell us about your web app project.',
  },
  {
    id: 'progressive-web-apps',
    name: 'Progressive Web Apps (PWA)',
    description: 'Creating fast and reliable PWAs for a seamless user experience.',
    whyChooseUs: 'PWAs combine the best of web and mobile apps, ensuring accessibility.',
    contactText: 'Inquire about our PWA solutions.',
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    description: 'Providing creative graphic design services for branding and marketing.',
    whyChooseUs: 'Our designs are visually appealing and aligned with your brand identity.',
    contactText: 'Let’s create stunning visuals for your brand.',
  },
  {
    id: 'software-development',
    name: 'Software Development',
    description: 'Custom software solutions tailored to your specific business needs.',
    whyChooseUs: 'We employ agile methodologies for flexible and adaptive software delivery.',
    contactText: 'Discuss your software requirements with us.',
  },
  {
    id: 'seo-services',
    name: 'SEO Services',
    description: 'Optimizing your website to improve visibility and drive organic traffic.',
    whyChooseUs: 'Our SEO strategies are designed to boost your online presence effectively.',
    contactText: 'Let’s talk about your SEO needs.',
  },
  {
    id: 'ai',
    name: 'AI Development',
    description: 'Integrating AI solutions to enhance your business operations.',
    whyChooseUs: 'We leverage cutting-edge AI technologies for innovative solutions.',
    contactText: 'Explore our AI development services.',
  },
  {
    id: 'blockchain',
    name: 'Blockchain Solutions',
    description: 'Developing secure blockchain solutions for various applications.',
    whyChooseUs: 'Our expertise ensures safe and transparent blockchain implementations.',
    contactText: 'Learn more about our blockchain services.',
  },
  {
    id: 'iot',
    name: 'IoT Solutions',
    description: 'Connecting devices and systems for smarter operations.',
    whyChooseUs: 'Our IoT solutions improve efficiency and enable data-driven decisions.',
    contactText: 'Inquire about our IoT capabilities.',
  },
  {
    id: 'data-science',
    name: 'Data Science & Analytics',
    description: 'Providing insights through data analysis to drive informed decision-making.',
    whyChooseUs: 'Our data science solutions help unlock the potential of your data.',
    contactText: 'Let’s analyze your data for better outcomes.',
  },
];

export default services;
